- src/components/Dashboard/ApisList/ApisListTable.tsx
- src/models/dashboard.ts
- Show the API version in the APIs list table as a new column
> feat: show api version in apis list table

- src/components/Dashboard/ApisList/ApisList.tsx
- src/components/Dashboard/ApisList/styled.tsx
- Namespace filtering for APIs table
> feat: apis namespace filter

- package-lock.json
- package.json
- src/components/TableOfContents/TableOfContents.tsx
- src/components/TableOfContents/styled.tsx
- src/models/ui.ts
- src/redux/initialState.ts
- src/redux/reducers/ui.ts
- Make the table of contents resizable in height
> feat: resizable table of contents

- src/components/Dashboard/ApiInfo/styled.tsx
- src/components/TableOfContents/TableOfContents.tsx
- src/components/TableOfContents/styled.tsx
- src/constants/constants.ts
- src/models/ui.ts
- src/pages/Dashboard/Dashboard.tsx
- src/pages/Dashboard/styled.tsx
- src/redux/initialState.ts
- src/redux/reducers/ui.ts
- src/swaggerUI/style.ts
- Add dashboard pane configuration
- Makes dashboard panes resizable
- Table of contents resizable width
> feat: resizable dashboard panes

- package-lock.json
- package.json
- src/components/KuskExtensions/KuskExtensions.tsx
- src/components/PostProcessedApiSpec/PostProcessedApiSpec.tsx
- src/components/RawApiSpec/RawApiSpec.tsx
- src/constants/kuskOpenApiSpec.json
- src/models/api.tsx
- src/utils/hooks.ts
- Update the client side according to the new OpenAPI Spec
> refactor: new api spec

- src/components/ApiDeployModal/ApiDeployModal.tsx
- API name validation for deployment
> feat: api name validation

- package-lock.json
- package.json
- src/components/ApiPublishModal/ApiPublishModal.tsx
- src/redux/reducers/main.ts
- Enable publish button, if mocking enabled, on the `API Info` step
- Enable publish button, if mocking disabled, on `Upstream | Redirect` step
> feat: publish button

- src/App.tsx
- src/components/ApiPublishModal/ApiPublishModal.tsx
- src/components/ApiPublishModal/styled.tsx
- src/components/NotificationBox/NotificationBox.tsx
- src/components/NotificationBox/index.ts
- src/components/index.ts
- src/models/alert.ts
- src/redux/initialState.ts
- src/redux/reducers/alert.ts
- src/redux/store.ts
- Add `NotificationBox` component and show success notification after publishing a new API
- Show error alert when trying to publish a new API
- Handle case when title is not found in OpenAPI Spec
> feat: api publish success notification + error alert

- package-lock.json
- package.json
- src/antd-theme/antd-customized.css
- src/antd-theme/antd-customized.less
- src/antd-theme/antd-theme.less
- src/index.tsx
- src/styles/colors.ts
- Add possibility to customize ANTD theme
- Change antd theme error color
> feat: customize antd theme + error color

- src/components/ApiPublishModal/ApiPublishModal.tsx
- src/components/ApiPublishModal/extensions/CORS.tsx
- src/components/FormList/FormList.tsx
- Change buttons hierarchy in API publish modal
- Add key for CORS methods checkboxes
> refactor: buttons hierarchy in publish modal

- src/components/ApiPublishModal/ApiPublishModal.tsx
- Add loading indicator on the publish button while "publishing" the API
- Disable the button while "publishing" the API
> feat: add loading on publish button + disable

- src/components/Apis/ApisList/ApisListTable.tsx
- src/components/Apis/ApisList/ApisListTableServicesTag.styled.tsx
- src/components/Apis/ApisList/ApisListTableServicesTag.tsx
- src/components/EnvoyFleets/EnvoyFleetsList/EnvoyFleetsListTable.tsx
- src/components/ListTableColumnLabel/ListTableColumnLabel.tsx
- src/components/ListTableColumnLabel/styled.tsx
- src/components/StaticRoutes/StaticRoutesList/StaticRoutesListTable.tsx
- src/styles/global.ts
- src/utils/listTable.ts
- make the whole row clickable (also make sure to add a cursor: pointer to it :))
- add a background to the whole row on hover (e.g. 3% white)
- add an active state to the whole row -> background on the whole row (e.g. 5% white) + bold white text + more opaque arrow
> refactor: improve table list item

- src/components/Apis/ApisList/ApisList.tsx
- src/components/Apis/ApisList/ApisListTable.tsx
- src/components/EnvoyFleets/EnvoyFleetsList/EnvoyFleetsList.tsx
- src/components/EnvoyFleets/EnvoyFleetsList/EnvoyFleetsListTable.tsx
- src/components/StaticRoutes/StaticRoutesList/StaticRoutesList.tsx
- src/components/StaticRoutes/StaticRoutesList/StaticRoutesListTable.tsx
- src/index.tsx
- src/models/main.ts
- src/pages/Settings/Settings.tsx
- src/pages/Settings/styled.tsx
- src/redux/initialState.ts
- src/redux/reducers/main.ts
- src/routes/index.tsx
- Gives the user the possibility to change the API endpoint ( saved in local storage and redux )
> feat: settings api endpoint

- src/components/ApiPublishModal/ApiInfo.tsx
- src/components/ApiPublishModal/OpenApiSpec.tsx
- src/components/ApiPublishModal/extensions/Path.tsx
- src/components/ApiPublishModal/extensions/QOS.tsx
- src/components/ApiPublishModal/extensions/Redirect.tsx
- src/components/ApiPublishModal/extensions/Upstream.tsx
- Add placeholders for API publish wizard inputs
> feat: add wizard input placeholders

- src/components/ApiDefinition/ApiDefinition.tsx
- src/components/ApiDefinition/index.ts
- src/components/ApiDefinition/styled.tsx
- src/components/Apis/ApiInfo/ApiInfo.tsx
- src/components/PostProcessedApiSpec/index.ts
- src/components/PublicApiDefinition/PublicApiDefinition.tsx
- src/components/PublicApiDefinition/index.ts
- src/components/PublicApiDefinition/styled.tsx
- src/components/RawApiSpec/index.ts
- src/components/index.ts
- Rename **RawApiSpec** to **ApiDefinition**
- Rename **PostProcessedApiSpec** to **PublicApiDefinition**
> refactor: components renaming

- src/components/TableOfContents/TableOfContents.tsx
- src/components/TableOfContents/styled.tsx
- src/swaggerUI/plugins/CollapseOperationsPlugin/CollapseOperationsPlugin.tsx
- src/swaggerUI/plugins/CollapseOperationsPlugin/styled.tsx
- src/swaggerUI/style.ts
- Make table of contents collapsible
> feat: collpasible table of contents

- src/components/Apis/ApisList/ApisList.tsx
- src/components/EnvoyFleets/EnvoyFleetInfo/APIs/APIs.tsx
- src/components/EnvoyFleets/EnvoyFleetInfo/APIs/styled.tsx
- src/components/EnvoyFleets/EnvoyFleetInfo/StaticRoutes/StaticRoutes.tsx
- src/components/EnvoyFleets/EnvoyFleetInfo/StaticRoutes/styled.tsx
- src/components/StaticRoutes/StaticRoutesList/StaticRoutesList.tsx
- src/models/main.ts
- src/redux/initialState.ts
- src/redux/reducers/main.ts
- Fleet APIs table on API select ( click ) : 
- Select the corresponding API from APIs list
- Switch menu tab to APIs list
- Fleet Static Routes table on Static Route select ( click ) : 
- Select the corresponding Static Route from Static Routes list
- Switch menu tab to Static Routes list
> feat: navigation improvement

- src/components/TableOfContents/TableOfContents.tsx
- src/models/ui.ts
- src/redux/initialState.ts
- src/redux/reducers/ui.ts
> refactor: rename table of contents heights

- src/components/Apis/ApiInfo/ApiInfo.tsx
- src/components/Apis/ApiInfo/CRD/CRD.tsx
- src/components/Apis/ApiInfo/CRD/index.ts
- src/models/dashboard.ts
- src/redux/initialState.ts
Issue: https://github.com/kubeshop/kusk-gateway/issues/358
- Added api CRD tab 
- set api CRD tab as a default tab
-
> fix: add api CRD tab

- src/constants/constants.ts
- src/index.tsx
- src/redux/reducers/main.ts
This PR...
-
- renamed target api local storage key
> fix: rename target api local storage key

- src/components/ApiPublishModal/ApiInfo.tsx
- src/components/ApiPublishModal/ApiPublishModal.tsx
- src/components/ApiPublishModal/FleetInfo.tsx
- src/models/api.tsx
- src/models/main.ts
- src/models/ui.ts
- src/utils/api.ts
> fix:publish api fleetInfo step 

- src/components/ApiPublishModal/ApiInfo.tsx
- src/components/Apis/ApisList/ApisList.tsx
- src/components/EnvoyFleets/EnvoyFleetsList/EnvoyFleetsList.tsx
- src/components/StaticRoutes/StaticRoutesList/StaticRoutesList.tsx
- src/models/api.tsx
This PR...
- filled dropdown with cluster namespaces
- filter data based on selected namespace
-
> fix: fill namespace dropdown from getNamespaces endpoint

- src/components/Apis/ApiInfo/ApiInfo.tsx
- src/components/EnvoyFleets/EnvoyFleetInfo/EnvoyFleetInfo.tsx
- src/components/StaticRoutes/StaticRouteInfo/StaticRouteInfo.tsx
> fix: popup confirmation message before delete a resource

- src/components/AddEnvoyFleetModal/AddEnvoyFleetModal.tsx
- src/components/AddEnvoyFleetModal/index.ts
- src/components/AddEnvoyFleetModal/styled.tsx
- src/components/EnvoyFleets/EnvoyFleetsList/EnvoyFleetsList.tsx
- src/components/EnvoyFleets/EnvoyFleetsList/styled.tsx
- src/models/api.tsx
- src/models/ui.ts
- src/pages/EnvoyFleets/EnvoyFleets.tsx
- src/redux/initialState.ts
- src/redux/reducers/ui.ts
> fix: createenvoyfleet from the dashboard

- src/components/AddEnvoyFleetModal/AddEnvoyFleetModal.tsx
- src/components/EnvoyFleets/EnvoyFleetsList/EnvoyFleetsList.tsx
- src/components/StaticRoutes/StaticRouteInfo/StaticRouteInfo.tsx
- src/components/StaticRoutes/StaticRoutesList/StaticRoutesList.tsx
> fix: close modal after submit form

- src/components/AddStaticRouteModal/AddPathModal/AddPathModal.tsx
- src/components/AddStaticRouteModal/AddStaticRouteModal.tsx
- src/components/AddStaticRouteModal/Paths.tsx
> fix: enable form submittion at last required step

- src/components/AddEnvoyFleetModal/AddEnvoyFleetModal.tsx
- src/components/AddStaticRouteModal/AddStaticRouteModal.tsx
- src/components/Apis/ApiInfo/ApiInfo.tsx
- src/components/EnvoyFleets/EnvoyFleetInfo/EnvoyFleetInfo.tsx
- src/components/StaticRoutes/StaticRouteInfo/StaticRouteInfo.tsx
> fix: use unwrap to catch failure

- src/components/AddEnvoyFleetModal/AddEnvoyFleetModal.tsx
- src/components/AddEnvoyFleetModal/FormStep.tsx
- src/components/AddEnvoyFleetModal/PortsInfo.tsx
> fix: fleetform steps

- package-lock.json
- src/components/ApiRawYaml/ApiRawYaml.tsx
- src/components/ApiRawYaml/index.ts
- src/components/ApiRawYaml/styled.tsx
- src/components/TableOfContents/TableOfContents.tsx
- src/components/TableOfContents/styled.tsx
> fix: show api yaml

- src/components/Apis/ApisList/ApisList.tsx
- src/components/EnvoyFleets/EnvoyFleetsList/EnvoyFleetsList.tsx
- src/components/StaticRoutes/StaticRoutesList/StaticRoutesList.tsx
> fix: handling api server errors

- src/analytics/AnalyticsService.ts
> fix: disable analytics

- src/components/ApiPublishModal/ApiPublishModal.tsx
- src/components/ApiPublishModal/extensions/Cache.tsx
- src/components/ApiPublishModal/styled.tsx
- src/models/ui.ts
> fix: add caching

- src/components/ApiPublishModal/ApiPublishModal.tsx
- src/components/ApiPublishModal/extensions/Cache.tsx
- src/components/ApiPublishModal/extensions/RateLimiting.tsx
- src/models/ui.ts
> fix: add api rate limiting

- src/components/ApiPublishModal/ApiPublishModal.tsx
- src/components/ApiPublishModal/extensions/CORS.tsx
- src/components/ApiPublishModal/extensions/Cache.tsx
- src/components/ApiPublishModal/extensions/QOS.tsx
This PR...
Fixes https://github.com/kubeshop/kusk-gateway/issues/500
-
> Fix typos and add units to time values

- .github/workflows/build.yml
- .github/workflows/release.yml
- Dockerfile
This PR supports docker build arg for SEGMENT_API_KEY
> Support setting of SEGMMENT_API_KEY in Dockerfile.

- src/components/AddEnvoyFleetModal/AddEnvoyFleetModal.tsx
- src/components/AddStaticRouteModal/AddPathModal/extension/Upstream.tsx
- src/components/AddStaticRouteModal/AddStaticRouteModal.tsx
- src/components/ApiPublishModal/ApiInfo.tsx
- src/components/ApiPublishModal/ApiPublishModal.tsx
- src/components/ApiPublishModal/OpenApiSpec.tsx
- src/components/ApiPublishModal/extensions/CORS.tsx
- src/components/ApiPublishModal/extensions/Hosts.tsx
- src/components/ApiPublishModal/extensions/Path.tsx
- src/components/ApiPublishModal/extensions/QOS.tsx
- src/components/ApiPublishModal/extensions/Redirect.tsx
- src/components/ApiPublishModal/extensions/Upstream.tsx
- src/components/ApiPublishModal/extensions/Validation.tsx
- src/components/ApiPublishModal/extensions/Websocket.tsx
- src/models/main.ts
- src/redux/initialState.ts
- src/redux/reducers/main.ts
> fix: remove depency between redux and ant forms

- src/components/ApiPublishModal/ApiPublishModal.tsx
- src/components/ApiPublishModal/OpenApiSpec.tsx
- src/components/ApiPublishModal/extensions/BasicAuthentication.tsx
- src/components/ApiPublishModal/extensions/RateLimiting.tsx
> fix: read x-kusk extension from spec

- public/index.html
- src/antd-theme/antd-theme.less
- src/styles/global.ts
> fix: use roboto font

- src/antd-theme/antd-theme.less
- src/components/Sidebar/DashboardMenu.styled.tsx
- src/components/Sidebar/DashboardMenu.tsx
- src/components/Sidebar/Sidebar.tsx
- src/components/Sidebar/styled.tsx
> fix: styling sidebar

- src/components/AddEnvoyFleetModal/AddEnvoyFleetModal.tsx
- src/components/AddStaticRouteModal/AddStaticRouteModal.tsx
- src/components/AddStaticRouteModal/Paths.tsx
- src/components/ApiPublishModal/ApiPublishModal.tsx
- src/components/Apis/ApisList/ApisList.tsx
- src/components/EnvoyFleets/EnvoyFleetsList/EnvoyFleetsList.tsx
- src/components/StaticRoutes/StaticRoutesList/StaticRoutesList.tsx
- src/redux/services/api.ts
> fix: publish forms error alert

- src/analytics/AnalyticsService.ts
- src/constants/constants.ts
> fix: add local storage analytics flag

- src/antd-theme/antd-customized.less
- src/antd-theme/antd-theme.less
- src/components/Apis/ApisList/ApisList.tsx
- src/components/Apis/ApisList/ApisListTable.styled.tsx
- src/components/Apis/ApisList/ApisListTable.tsx
- src/components/Apis/ApisList/styled.tsx
- src/components/HelpCard/HelpCard.tsx
- src/components/HelpCard/index.ts
- src/components/HelpCard/styled.tsx
> fix: apis list

- src/components/ApiDetails/ApiDetails.tsx
- src/components/Header/Header.tsx
- src/components/Header/styled.tsx
> fix: polish api page

- src/components/ApiPublishModal/CanvasApiModal.tsx
> fix: api modal title

- src/components/ApiDetails/Sidebar/Sidebar.tsx
> fix: Paths tooltip

- src/redux/services/kuskApi.ts
> fix: apis url

- src/components/Header/Header.tsx
> fix: call apis list only on api detail page

- package.json
> fix: remove proxy  package.json

- public/_redirects
> fix: netlfu proxy

- public/_redirects
> fix: update netlify api

- src/antd-theme/antd-theme.less
- src/components/ApiSettings/Settings/General.tsx
- src/components/Apis/ApisList/ApisListTable.tsx
> fix: stop menu click propagation

- src/components/Apis/ApisList/ApisListTable.tsx
- src/components/Header/Header.tsx
> fix: add click handler toheader dropdown list

- src/components/ApiPublishModal/CanvasApiModal.tsx
> fix:  api form validate name when select namespace

- src/components/ApiSettings/Settings/General.tsx
- src/components/Apis/ApisList/ApisListTable.tsx
> fix: update delete message

- src/components/ApiPublishModal/CanvasApiModal.tsx
- src/components/Header/Header.tsx
> fix: navigate after submit api form

- src/components/ApiDetails/ApiDetails.tsx
- src/components/ApiPublishModal/CanvasApiModal.tsx
- src/components/Apis/ApisList/ApisListTable.tsx
- src/components/Header/Header.tsx
- src/index.tsx
- src/redux/services/api.ts
- src/routes/index.tsx
> fix: api details page url

- src/index.tsx
> fix: fallback to default of missed

- src/components/Apis/ApisList/ApisListTable.tsx
> fix: prevent event propagation on menu

- package-lock.json
- package.json
- src/components/ApiSettings/Settings/AddTargetModal/AddTargetModal.tsx
- src/components/ApiSettings/Settings/AddTargetModal/Targets/Redirect.tsx
- src/components/ApiSettings/Settings/AddTargetModal/Targets/Upstream.tsx
- src/components/ApiSettings/Settings/AddTargetModal/Targets/styled.tsx
- src/components/ApiSettings/Settings/Authentication.tsx
- src/components/ApiSettings/Settings/CORS.tsx
- src/components/ApiSettings/Settings/Caching.tsx
- src/components/ApiSettings/Settings/Deployments.tsx
- src/components/ApiSettings/Settings/General.tsx
- src/components/ApiSettings/Settings/Hosts.tsx
- src/components/ApiSettings/Settings/QOS.tsx
- src/components/ApiSettings/Settings/RateLimiting.tsx
- src/components/FormCard/FormCard.tsx
- src/redux/reducers/main.ts
- src/redux/services/enhancedApi.ts
- src/redux/services/kuskApi.ts
> fix: form update

- .github/workflows/build.yml
- .github/workflows/release.yml
- Dockerfile
> build dashboard for arm64 architectures

- src/components/AddEnvoyFleetModal/AddEnvoyFleetModal.tsx
> fix: passing target ports as string

- src/components/Header/Header.tsx
> fix: add help menu

- src/components/Monaco/Monaco.tsx
- src/styles/colors.ts
- src/utils/Monaco.ts
This PR...
first iteration to update Monaco styles (abstracted colors are pending #210 :))
-
> feat: update monaco styles

- src/components/ApiDashboard/ApiDashboard.tsx
- src/components/ApiDashboard/index.ts
- src/components/ApiDeployments/ApiDeployments.tsx
- src/components/ApiDeployments/index.ts
- src/components/ApiDetails/ApiDetails.tsx
- src/components/ApiDetails/Sidebar/Sidebar.tsx
- src/components/ApiLogs/ApiLogs.tsx
- src/components/ApiLogs/index.ts
> fix: alter api details unused section

- src/antd-theme/antd-theme.less
> fix: system design  typography

- src/styles/global.ts
> fix: add form item margin bottom

- src/antd-theme/antd-theme.less
- src/components/AddEnvoyFleetModal/AddEnvoyFleetModal.tsx
- src/components/AntdCustom/index.tsx
- src/components/ApiPublishModal/ApiCreatorModal.tsx
- src/components/ApiPublishModal/CanvasApiModal.tsx
- src/components/ApiPublishModal/styled.tsx
- src/pages/Apis/Apis.tsx
- src/styles/colors.ts
- src/styles/global.ts
> fix: form required fields

- src/components/ApiOpenSpec/CRD.styled.tsx
- src/components/ApiOpenSpec/KuskExtension.styled.tsx
- src/components/ApiOpenSpec/KuskExtension.tsx
- src/components/ApiOpenSpec/OpenApiEditor.styled.tsx
- src/components/ApiOpenSpec/OpenApiEditor.tsx
- src/components/InfoPaneCRD/InfoPaneCRD.tsx
- src/components/Monaco/Monaco.styled.tsx
- src/components/Monaco/Monaco.tsx
> fix: crd double scroll

- public/_redirects
> fix: update api ip

- src/components/ApiSettings/Settings/General.tsx
- src/redux/reducers/main.ts
> fix: update api settings

- src/antd-theme/antd-theme.less
- src/components/ApiSettings/Settings/styled.tsx
> fix: btn danger styling

- public/_redirects
> fix: change ip

- src/antd-theme/antd-theme.less
- src/components/FormCard/styled.tsx
> fix: btn disabled hover

- src/components/FormCard/FormCard.tsx
> fix: reset form after submit

- src/components/ApiDetails/Api404/Api404.tsx
- src/components/ApiRoutes/ApiRoutes.tsx
- src/components/ApiSettings/Settings/Targets.tsx
- src/components/Apis/ApisList/ApisList.tsx
- src/components/FormCard/FormCard.tsx
- src/components/Settings/DeploymentsSettings/DeploymentsSettings.tsx
- src/components/Settings/KuskSettings/KuskSettings.tsx
- src/components/StaticRoutes/StaticRoutesList/StaticRoutesList.tsx
> fix: btn size

- src/components/Apis/ApisList/styled.tsx
> fix: dashboard filter align items

- src/components/ApiPublishModal/CanvasApiModal.tsx
- src/components/ApiPublishModal/FileApiModal.tsx
> fix: api url error

- src/components/AntdCustom/index.tsx
- src/components/ApiPaths/ApiPaths.tsx
> fix: remove expand icon

- src/components/ApiSettings/Settings/General.tsx
> fix: api settings disable name

- src/antd-theme/antd-theme.less
> fix: theme primary color

- src/components/StaticRouteDetails/RouteInfo/RouteInfo.tsx
- src/redux/reducers/main.ts
> fix: update static route envoy fleet

- src/components/AntdCustom/index.tsx
> fix: operation tag uppercase

- src/components/ApiDetails/ApiDetails.tsx
- src/components/ApiDetails/Sidebar/Sidebar.tsx
- src/components/ApiOpenSpec/ApiOpenSpec.tsx
- src/components/ApiPaths/ApiPaths.tsx
- src/components/ApiSettings/ApiSettings.tsx
- src/components/ApiSettings/Settings/Authentication.tsx
- src/components/ApiSettings/Settings/CORS.tsx
- src/components/ApiSettings/Settings/Caching.tsx
- src/components/ApiSettings/Settings/General.tsx
- src/components/ApiSettings/Settings/Hosts.tsx
- src/components/ApiSettings/Settings/QOS.tsx
- src/components/ApiSettings/Settings/RateLimiting.tsx
- src/components/ApiSettings/Settings/Targets.tsx
- src/components/Header/Header.tsx
- src/components/Settings/Settings.tsx
- src/components/StaticRouteDetails/StaticRouteDetails.tsx
- src/constants/constants.ts
- src/models/ui.ts
- src/redux/listeners/ApiListener.ts
- src/redux/reducers/main.ts
- src/routes/index.tsx
> fix: url navigation

- src/components/Home/Header/Header.tsx
- src/components/Home/Header/styled.tsx
- src/styles/colors.ts
> fix: nav menu hover

- src/components/Home/Header/Header.tsx
> fix: release url

- src/components/Home/Header/styled.tsx
> fix: nav menu width

- src/components/ApiDetails/ApiSettings/Settings/Target/EditTarget/EditTarget.tsx
- src/components/Target/EditTarget/EditTarget.tsx
- src/components/TargetForm/TargetForm.tsx
- src/components/TargetForm/styled.tsx
> fix: target type selector

- src/components/ApiDetails/ApiSettings/Settings/Authentication.tsx
- src/components/ApiDetails/ApiSettings/Settings/Targets.tsx
> fix: direct url fail on null

- src/components/AntdCustom/index.tsx
- src/components/StaticRoutes/styled.tsx
> fix: fit screen size

- src/components/AddStaticRouteModal/PathForm.tsx
- src/components/StaticRouteDetails/PathSettings/PathInfo.styled.tsx
- src/components/StaticRouteDetails/PathSettings/PathInfo.tsx
- src/components/StaticRouteDetails/Paths/AddPathModal/AddPathModal.tsx
- src/components/StaticRouteDetails/Paths/AddPathModal/styled.tsx
> fix: enable get method for static route by default

- src/components/Apis/ApisList/EmptyApisList.styled.tsx
- src/components/Apis/ApisList/EmptyApisList.tsx
> fix: empty api labels

- src/components/StaticRouteDetails/PathSettings/PathSettings.tsx
> fix: disable delete path

- src/components/StaticRoutes/StaticRoutes.tsx
> fix: delete static route

- src/antd-theme/antd-theme.less
- src/components/ApiDetails/Api404/Api404.tsx
- src/components/ApiDetails/ApiSettings/Settings/General.tsx
- src/components/ApiDetails/ApiSettings/Settings/Target/EditTarget/EditTarget.tsx
- src/components/ApiDetails/ApiSettings/Settings/Targets.tsx
- src/components/ApiDetails/ApiSkelton/ApiSkelton.tsx
- src/components/Apis/ApisList/ApisList.tsx
- src/components/FormComponents/FormCard/FormCard.tsx
- src/components/Settings/DeploymentsSettings/DeploymentsSettings.tsx
- src/components/Settings/KuskSettings/KuskSettings.tsx
- src/components/StaticRouteDetails/Paths/Paths.tsx
- src/components/StaticRoutes/StaticRoutes.tsx
- src/components/Target/EditTarget/EditTarget.tsx
> fix: default item size

- src/components/AddStaticRouteModal/AddStaticRouteModal.tsx
- src/components/ApiDetails/Api404/Api404.tsx
- src/components/ApiPublishModal/CanvasApiModal.tsx
- src/components/ApiPublishModal/FileApiModal.tsx
- src/components/Apis/ApisList/ApisListTable.tsx
- src/components/Header/Header.tsx
- src/components/Home/Header/Header.tsx
- src/components/Settings/Settings.tsx
- src/components/StaticRouteDetails/StaticRouteDetails.tsx
- src/components/StaticRoutes/StaticRoutes.tsx
- src/constants/AppRoutes.ts
- src/routes/index.tsx
> fix: app routing

- public/index.html
- src/antd-theme/antd-theme.less
- src/swaggerUI/style.ts
> fix: roboto font

- src/components/Apis/ApisList/ApisList.tsx
> fix: apis namespace filter

- src/components/ApiDetails/ApiSkelton/ApiSkelton.tsx
- src/components/ApiDetails/ApiSkelton/styled.tsx
- src/components/Apis/ApisList/ApisList.tsx
- src/components/Apis/ApisList/styled.tsx
- src/components/Header/Header.tsx
- src/components/Home/Home.tsx
- src/components/Settings/DeploymentsSettings/DeploymentsSettings.tsx
- src/components/Skeletons/Skeletons.tsx
- src/components/Skeletons/index.ts
- src/components/StaticRouteDetails/Hosts/Hosts.tsx
- src/components/StaticRouteDetails/Paths/Paths.tsx
- src/components/StaticRouteDetails/RouteInfo/RouteInfo.tsx
- src/components/StaticRouteDetails/StaticRouteDetails.tsx
- src/components/StaticRoutes/StaticRoutes.tsx
> fix: add skeletons

- src/components/Apis/ApisList/ApisList.tsx
> fix: create api label

- src/components/Apis/ApisList/ApisListTable.styled.tsx
- src/components/Apis/ApisList/ApisListTable.tsx
- src/components/Apis/ApisList/styled.tsx
- src/styles/colors.ts
> fix: dashboard colors

- src/components/Apis/ApisList/ApisList.tsx
- src/components/HelpCard/HelpCard.tsx
- src/constants/constants.ts
> fix: default docs link

- src/antd-theme/antd-theme.less
- src/components/Apis/ApisList/ApisListTable.styled.tsx
> fix: font weight

- src/components/Home/Home.tsx
> fix: test path for routing

- src/components/ApiDetails/ApiDetails.tsx
> fix: api details skeleton

- src/App.tsx
> fix: remove global app skeleton

- src/App.tsx
Reverts kubeshop/kusk-gateway-dashboard#287
> Revert "fix: remove global app skeleton"

- src/components/ApiDetails/ApiSettings/Settings/General.tsx
- src/redux/reducers/main.ts
> fix: edit display name

- src/components/ApiDetails/ApiPaths/ApiPaths.tsx
> fix: filter api operations

- src/antd-theme/antd-theme.less
> fix: skeleton color

- src/components/FormComponents/FormCard/FormCard.tsx
- src/components/Settings/KuskSettings/KuskSettings.tsx
> fix: form card cancel edit mode

- src/components/ApiPublishModal/CanvasApiModal.tsx
- src/components/ApiPublishModal/styled.tsx
- src/utils/api.ts
> fix: remove form warnings

- src/components/AddStaticRouteModal/PathForm.tsx
- src/components/StaticRouteDetails/PathSettings/PathInfo.tsx
- src/components/StaticRouteDetails/Paths/AddPathModal/AddPathModal.tsx
> fix: edit path name validation

- src/components/AddEnvoyFleetModal/AddEnvoyFleetModal.tsx
- src/components/AddStaticRouteModal/AddStaticRouteModal.tsx
- src/components/AddStaticRouteModal/PathForm.tsx
- src/components/AddStaticRouteModal/RouteInfoForm.tsx
- src/components/ApiDetails/ApiSettings/Settings/Authentication.tsx
- src/components/ApiDetails/ApiSettings/Settings/Deployments.tsx
- src/components/ApiDetails/ApiSettings/Settings/General.tsx
- src/components/ApiDetails/ApiSettings/Settings/Target/EditTarget/Redirect.tsx
- src/components/ApiDetails/ApiSettings/Settings/Target/EditTarget/Upstream.tsx
- src/components/ApiPublishModal/CanvasApiModal.tsx
- src/components/ApiPublishModal/FileApiModal.tsx
- src/components/FormComponents/FormCard/FormCard.tsx
- src/components/Settings/KuskSettings/KuskSettings.tsx
- src/components/StaticRouteDetails/PathSettings/PathInfo.tsx
- src/components/StaticRouteDetails/Paths/AddPathModal/AddPathModal.tsx
- src/components/StaticRouteDetails/RouteInfo/RouteInfo.tsx
- src/components/Target/EditTarget/Redirect.tsx
- src/components/Target/EditTarget/Upstream.tsx
- src/components/TargetForm/Targets/Redirect.tsx
- src/components/TargetForm/Targets/Upstream.tsx
> fix: error messages

- src/components/Apis/ApisList/ApisList.tsx
- src/components/Apis/ApisList/ApisListTable.tsx
- src/components/Apis/ApisList/styled.tsx
> fix: apis fleet filter

- src/components/ApiDetails/ApiDetails.tsx
- src/components/ApiDetails/ApiSettings/Settings/CORS.tsx
- src/components/FormComponents/FormCard/FormCard.tsx
> fix: cors max_age default value

- src/components/AddEnvoyFleetModal/AddEnvoyFleetModal.tsx
- src/components/AddStaticRouteModal/RouteInfoForm.tsx
> fix: resource name validation

- README.md
- src/components/ApiDetails/ApiSettings/ApiSettings.tsx
- src/components/ApiDetails/ApiSettings/Settings/Authentication.tsx
- src/components/ApiDetails/ApiSettings/Settings/Caching.tsx
- src/components/ApiDetails/ApiSettings/Settings/Deployments.tsx
- src/components/ApiDetails/ApiSettings/Settings/General.tsx
- src/components/ApiDetails/ApiSettings/Settings/Hosts.tsx
- src/components/ApiDetails/ApiSettings/Settings/QOS.tsx
- src/components/ApiDetails/ApiSettings/Settings/RateLimiting.tsx
- src/components/ApiDetails/ApiSettings/Settings/Targets.tsx
- src/components/Apis/ApisList/EmptyApisList.tsx
- src/components/StaticRouteDetails/PathSettings/CORS.tsx
- src/components/StaticRouteDetails/PathSettings/PathTarget.tsx
- src/components/StaticRouteDetails/PathSettings/QOS.tsx
- src/components/StaticRouteDetails/PathSettings/Websocket.tsx
- src/constants/kuskOpenApiSpec.json
> fix: update docs link

- src/components/ApiDetails/ApiSettings/Settings/Authentication.tsx
- src/constants/rawOpenApiSpec.json
> fix: custom auth

- src/components/KuskApiDown/KuskApisDown.tsx
- src/components/Settings/KuskSettings/KuskSettings.tsx
- src/components/Settings/Settings.tsx
- src/constants/kuskOpenApiSpec.json
- src/constants/tooltips.ts
> fix: capitalize kusk

- src/components/ApiPublishModal/CanvasApiModal.tsx
- src/components/ApiPublishModal/FileApiModal.tsx
> fix: deploy api mocking false

- src/components/ApiPublishModal/CanvasApiModal.tsx
- src/components/ApiPublishModal/FileApiModal.tsx
Reverts kubeshop/kusk-gateway-dashboard#323
> Revert "fix: deploy api mocking false"

- src/components/ApiDetails/ApiPaths/ApiPolicies/ApiPolicies.tsx
- src/components/ApiDetails/ApiPaths/ApiPolicies/Policies.tsx
- src/components/ApiDetails/ApiPaths/ApiPolicies/PoliciesList.styled.tsx
- src/components/ApiDetails/ApiPaths/ApiPolicies/PoliciesList.tsx
- src/components/FormComponents/FormCard/FormCard.tsx
- src/components/PathNavigator/PathNavigator.tsx
- src/components/Policies/TargetForm/TargetForm.tsx
- src/components/Policies/TargetForm/Targets/Mocking.tsx
- src/components/Policies/TargetForm/Targets/Redirect.tsx
- src/components/Policies/TargetForm/Targets/Upstream.tsx
- src/components/Policies/TargetForm/Targets/styled.tsx
- src/components/Policies/TargetForm/index.ts
- src/components/Policies/Targets.tsx
> fix: policies list

- src/components/ApiDetails/ApiPaths/ApiPaths.tsx
- src/components/ApiDetails/ApiPaths/ApiPathsTable/ApiPathsTable.tsx
- src/components/ApiDetails/ApiPaths/ApiPolicies/ApiPolicies.tsx
- src/constants/rawOpenApiSpec.json
> fix: update paths table

- src/components/ApiDetails/ApiPaths/ApiPaths.tsx
- src/components/ApiDetails/Sidebar/Sidebar.tsx
> fix: api paths title

- src/components/ApiDetails/ApiPaths/styled.tsx
> fix: routing section scrolling

- src/components/ApiDetails/ApiPaths/ApiPolicies/ApiPolicies.tsx
> fix: back to list policies

- src/components/Policies/TargetForm/Targets/Upstream.tsx
> fix: fill  upstream policy select

- src/components/PathNavigator/PathNavigator.tsx
> fix: policies navigation

- src/components/ApiDetails/ApiPaths/ApiPathsTable/ApiPathsTable.tsx
- src/components/PathNavigator/styled.tsx
> fix:  polish policies table

- src/components/Policies/TargetForm/Targets/Upstream.tsx
> fix: upstream default value

- src/components/ApiDetails/ApiPaths/ApiPolicies/PoliciesList.tsx
> fix: policy name

- src/components/PathNavigator/PathNavigator.tsx
> fix: rename hidden to disable

- src/antd-theme/antd-theme.less
- src/components/ApiDetails/ApiPaths/ApiPathsTable/ApiPathsTable.tsx
- src/components/ApiDetails/ApiPaths/ApiPolicies/Policies.styled.tsx
- src/components/ApiDetails/ApiPaths/ApiPolicies/Policies.tsx
- src/components/ApiDetails/ApiPaths/styled.tsx
- src/components/ApiDetails/ApiSettings/Settings/CORS.tsx
- src/components/FormComponents/FormList/FormList.tsx
- src/components/PathNavigator/PathNavigator.tsx
- src/components/PathNavigator/styled.tsx
- src/components/Policies/Authentication.tsx
- src/components/Policies/CORS.tsx
- src/components/Policies/Caching.tsx
- src/components/Policies/QOS.tsx
- src/components/Policies/RateLimiting.tsx
- src/components/StaticRouteDetails/PathSettings/CORS.tsx
- src/styles/colors.ts
> fix: polish policies

- src/components/FormComponents/FormList/FormList.tsx
> fix: form list duplicated values

- package-lock.json
- package.json
> fix: testing dependencies

- src/components/ApiDetails/ApiOpenSpec/KuskExtension.tsx
- src/components/ApiDetails/ApiOpenSpec/OpenApiEditor.tsx
- src/components/InfoPaneCRD/InfoPaneCRD.tsx
> fix: split monaco from main file

- src/components/ApiDetails/ApiSettings/Settings/CORS.tsx
- src/components/ApiDetails/ApiSettings/Settings/Hosts.tsx
- src/components/FormComponents/FormList/FormList.tsx
- src/components/Policies/CORS.tsx
- src/components/StaticRouteDetails/Hosts/Hosts.tsx
- src/components/StaticRouteDetails/PathSettings/CORS.tsx
> fix: cors required list

- src/antd-theme/antd-theme.less
> fix: h5 font-weight

- src/components/ApiDetails/ApiSettings/styled.tsx
> fix: layout shifting while scrolling

- src/components/PathNavigator/styled.tsx
> fix: path navigator ellipsis

- src/components/ApiDetails/ApiPaths/ApiPolicies/PoliciesList.styled.tsx
- src/components/ApiDetails/ApiPaths/ApiPolicies/PoliciesList.tsx
- src/components/PathNavigator/PathNavigator.tsx
> fix: disabled

- openapi-config.ts
- src/components/ApiDetails/ApiOpenSpec/OpenApiEditor.styled.tsx
- src/components/ApiDetails/ApiOpenSpec/OpenApiEditor.tsx
- src/components/ApiDetails/ApiPaths/ApiPolicies/ApiPolicies.tsx
- src/components/ApiDetails/ApiPaths/ApiPolicies/Policies.tsx
- src/components/Policies/42Crunch.tsx
- src/components/Policies/index.ts
- src/redux/services/kuskApi.ts
> fix: 42crunch
